/* 
	### 주차장 관리 테이블 3개 
*/

CREATE TABLE PRKPLCE_MNG
(
	PRKPLCE_CODE	VARCHAR(6)		NOT NULL, /* 주차장코드(대분류코드) */
	PRKPLCE_NM		VARCHAR(50)	NULL	, /* 주차장명 */
	RM				VARCHAR(200)	NULL	/* 비고 */
	
	,PRIMARY KEY (PRKPLCE_CODE)
);

CREATE UNIQUE INDEX PRKPLCE_MNG_PK ON PRKPLCE_MNG
(
	PRKPLCE_CODE
)
;

CREATE TABLE PRKPLCE_FLR_MNG
(
	PRKPLCE_CODE		VARCHAR(6)		NOT NULL,
	PRKPLCE_FLR_CODE	VARCHAR(6)		NOT NULL,
	PRKPLCE_FLR_NM		VARCHAR(200)	NULL,
	DRW_PATH			VARCHAR(200)	NULL,
	SORT				INT(2)			NULL,
	RM					VARCHAR(200)	NULL
	
	,PRIMARY KEY ( PRKPLCE_CODE, PRKPLCE_FLR_CODE )
);

CREATE UNIQUE INDEX PRKPLCE_FLR_MNG_PK ON PRKPLCE_FLR_MNG
(
	PRKPLCE_CODE, PRKPLCE_FLR_CODE
)
;


CREATE TABLE PRKPLCE_CELL_MNG
(
	PRKPLCE_CODE		VARCHAR(6)		NOT NULL,
	PRKPLCE_FLR_CODE	VARCHAR(6)		NOT NULL,
	CELL_MAPNG_ID		VARCHAR(50)		NOT NULL,
	CELL_TYPE			VARCHAR(15)		NOT NULL,
	STYLE_CLS			VARCHAR(150)	NULL	,
	SALE_CAR_INNB		VARCHAR(10)		NULL	,
	X					VARCHAR(15)		NOT NULL,
	Y					VARCHAR(15)		NOT NULL,
	WIDTH				VARCHAR(10)		NOT NULL,
	HEIGHT				VARCHAR(10)		NOT NULL
	
	
	
	,PRIMARY KEY ( PRKPLCE_CODE, PRKPLCE_FLR_CODE , CELL_MAPNG_ID)
);

CREATE UNIQUE INDEX PRKPLCE_CELL_MNG_PK ON PRKPLCE_CELL_MNG
(
	PRKPLCE_CODE, PRKPLCE_FLR_CODE , CELL_MAPNG_ID
)
;

-- 공통코드테이블 하나로 관리



/*  ====================================================================  */
/* 
	### 공통코드 테이블 3개 
	[1] 대분류코드 - CMMN_CODE_GROUP 
	[2] 중분류코드 - CMMN_CODE_DIV
	[3] 소분류코드 - CMMN_CODE_DETAIL
	
*/

-- 대분류
CREATE TABLE CMMN_CODE_GROUP
(
	GROUP_CODE		CHAR(3)		NOT NULL, /* 그룹코드(대분류코드) */
	GROUP_CODE_NM	VARCHAR(60)	NULL	, /* 그룹코드명 */
	GROUP_CODE_DC	VARCHAR(200)	NULL	, /* 그룹코드설명 */
	USE_AT			CHAR(1)		NULL	, /* 사용여부 */
	FRST_REGIST_DT	DATETIME	NULL	, /* 처음등록일시 */
	FRST_REGISTER	VARCHAR(20)	NULL	, /* 처음등록자 */
	LAST_REGIST_DT	DATETIME	NULL	, /* 마지막등록일시 */
	LAST_REGISTER	VARCHAR(20)	NULL	, /* 마지막등록자 */
	PRIMARY KEY (GROUP_CODE)
);

CREATE UNIQUE INDEX CMMN_CODE_GROUP_PK ON CMMN_CODE_GROUP
(
	GROUP_CODE
)
;



-- 중분류 
CREATE TABLE CMMN_CODE_DIV
(
	GROUP_CODE  	CHAR(3)		NULL	, /* 그룹코드(대분류코드) */    
	DIV_CODE		VARCHAR(6)	NOT NULL, /* 구분코드(중분류코드) */
	DIV_CODE_NM 	VARCHAR(60)	NULL	, /* 구분코드명 */
	DIV_CODE_DC 	VARCHAR(200)	NULL	, /* 구분코드설명 */
	USE_AT      	CHAR(1)		NULL	, /* 사용여부 */
	FRST_REGIST_DT	DATETIME	NULL	, /* 처음등록일시 */
	FRST_REGISTER 	VARCHAR(20)	NULL	, /* 처음등록자 */
	LAST_REGIST_DT	DATETIME	NULL	, /* 마지막등록일시 */
	LAST_REGISTER 	VARCHAR(20)	NULL	, /* 마지막등록자 */
	PRIMARY KEY (DIV_CODE)
);

CREATE UNIQUE INDEX CMMN_CODE_DIV_PK ON CMMN_CODE_DIV
(
	DIV_CODE
	,GROUP_CODE
);



-- 소분류
CREATE TABLE CMMN_CODE_DETAIL
(
	GROUP_CODE  	CHAR(3)		NOT NULL	, /* 그룹코드(대분류코드) */	
	DIV_CODE		VARCHAR(6)	NOT NULL, /* 분류코드(중분류코드) */
	CODE			VARCHAR(15)	NOT NULL, /* 코드(소분류코드) */
	CODE_NM			VARCHAR(60)	NULL	, /* 코드명 */
	CODE_DC			VARCHAR(200)	NULL	, /* 코드설명 */
	USE_AT			CHAR(1)		NULL	, /* 사용여부 */
	SORT			INT(3)		NULL	,
	FRST_REGIST_DT	DATETIME	NULL	, /* 처음등록일시 */
	FRST_REGISTER 	VARCHAR(20)	NULL	, /* 처음등록자 */
	LAST_REGIST_DT	DATETIME	NULL	, /* 마지막등록일시 */
	LAST_REGISTER 	VARCHAR(20)	NULL	, /* 마지막등록자 */
	PRIMARY KEY (DIV_CODE,CODE)
)
;

CREATE UNIQUE INDEX CMMN_CODE_DETAIL_PK ON CMMN_CODE_DETAIL
(
	GROUP_CODE,
	DIV_CODE,
	CODE
)
;