/* 
	### 주차장 관리 테이블 3개 
*/

CREATE TABLE PRKPLCE_MNG
(
	PRKPLCE_CODE	VARCHAR(6)		NOT NULL, /* 주차장코드(대분류코드) */
	PRKPLCE_NM		VARCHAR(50)	NULL	, /* 주차장명 */
	RM				VARCHAR(200)	NULL	/* 비고 */
	
	,PRIMARY KEY (PRKPLCE_CODE)
);

CREATE UNIQUE INDEX PRKPLCE_MNG_PK ON PRKPLCE_MNG
(
	PRKPLCE_CODE
)
;

CREATE TABLE PRKPLCE_FLR_MNG
(
	PRKPLCE_CODE		VARCHAR(6)		NOT NULL,
	PRKPLCE_FLR_CODE	VARCHAR(6)		NOT NULL,
	PRKPLCE_FLR_NM		VARCHAR(200)	NULL,
	DRW_PATH			VARCHAR(200)	NULL,
	DRW_SIZE_WIDTH		VARCHAR(10)			NULL,
	DRW_SIZE_HEIGHT		VARCHAR(10)			NULL,
	SORT				INT(2)			NULL,
	RM					VARCHAR(200)	NULL
	
	,PRIMARY KEY ( PRKPLCE_CODE, PRKPLCE_FLR_CODE )
);

CREATE UNIQUE INDEX PRKPLCE_FLR_MNG_PK ON PRKPLCE_FLR_MNG
(
	PRKPLCE_CODE, PRKPLCE_FLR_CODE
)
;


CREATE TABLE PRKPLCE_CELL_MNG
(
	PRKPLCE_CODE		VARCHAR(6)		NOT NULL,
	PRKPLCE_FLR_CODE	VARCHAR(6)		NOT NULL,
	CELL_MAPNG_ID		VARCHAR(50)		NOT NULL,
	CELL_TYPE			VARCHAR(15)		NOT NULL,
	STYLE_CLS			VARCHAR(150)	NULL	,
	SALE_CAR_INNB		VARCHAR(10)		NULL	,
	X					VARCHAR(15)		NULL,
	Y					VARCHAR(15)		NULL,
	TRANSFORM			VARCHAR(200)	NULL,
	SHAPE				VARCHAR(50)		NULL,
	WIDTH				VARCHAR(10)		NOT NULL,
	HEIGHT				VARCHAR(10)		NOT NULL
	
	
	
	,PRIMARY KEY ( PRKPLCE_CODE, PRKPLCE_FLR_CODE , CELL_MAPNG_ID)
);

CREATE UNIQUE INDEX PRKPLCE_CELL_MNG_PK ON PRKPLCE_CELL_MNG
(
	PRKPLCE_CODE, PRKPLCE_FLR_CODE , CELL_MAPNG_ID
)
;

-- svg 객체 관리 테이블
CREATE TABLE SVG_OBJECT_INFO
(
	CELL_TYPE			VARCHAR(15)		NOT NULL,
	CELL_NM				VARCHAR(15)		NULL,
	SHAPE				VARCHAR(20)		NULL,
	STYLE				VARCHAR(200)	NULL,
	STYLE_CLS			VARCHAR(200)	NULL,
	FILL				VARCHAR(20)		NULL,
	STROKE				VARCHAR(5)		NULL,
	STROKE_WIDTH		VARCHAR(5)		NULL,
	STROKE_DASHARRAY	VARCHAR(20)		NULL,
	STROKE_LINECAP		VARCHAR(20)		NULL,
	FILL_OPACITY		VARCHAR(5)		NULL,
	STROKE_OPACITY		VARCHAR(5)		NULL,
	CX					VARCHAR(15)		NULL,
	CY					VARCHAR(15)		NULL,
	RX					VARCHAR(15)		NULL,
	RY					VARCHAR(15)		NULL,
	R					VARCHAR(15)		NULL,
	X					VARCHAR(15)		NULL,
	Y					VARCHAR(15)		NULL,
	X1					VARCHAR(15)		NULL,
	Y1					VARCHAR(15)		NULL,
	X2					VARCHAR(15)		NULL,
	Y2					VARCHAR(15)		NULL,
	D					VARCHAR(500)	NULL,
	DX					VARCHAR(15)		NULL,
	DY					VARCHAR(15)		NULL,
	POINTS				VARCHAR(200)	NULL,
	TRANSFORM			VARCHAR(200)	NULL,
	WIDTH				VARCHAR(10)		NULL,
	HEIGHT				VARCHAR(10)		NULL,
	
	PRIMARY KEY ( CELL_TYPE )
);

CREATE UNIQUE INDEX SVG_OBJECT_INFO_PK ON SVG_OBJECT_INFO
(
	CELL_TYPE
)
;

INSERT INTO `lfc`.`svg_object_info` (`CELL_TYPE`, `CELL_NM`, `SHAPE`, `STYLE_CLS`, `TRANSFORM`, `WIDTH`, `HEIGHT`) VALUES ('P0', '', 'rect', 'box P0', 'translate(0,0)', '20', '30');
INSERT INTO `lfc`.`svg_object_info` (`CELL_TYPE`, `CELL_NM`, `SHAPE`, `STYLE_CLS`, `TRANSFORM`, `WIDTH`, `HEIGHT`) VALUES ('P1', '', 'rect', 'box P1', 'translate(0,0)', '20', '30');
INSERT INTO `lfc`.`svg_object_info` (`CELL_TYPE`, `CELL_NM`, `SHAPE`, `STYLE_CLS`, `TRANSFORM`, `WIDTH`, `HEIGHT`) VALUES ('P2', '', 'rect', 'box P2', 'translate(0,0)', '20', '30');
INSERT INTO `lfc`.`svg_object_info` (`CELL_TYPE`, `CELL_NM`, `SHAPE`, `STYLE_CLS`, `TRANSFORM`, `WIDTH`, `HEIGHT`) VALUES ('P3', '', 'rect', 'box P3', 'translate(0,0)', '20', '30');
INSERT INTO `lfc`.`svg_object_info` (`CELL_TYPE`, `CELL_NM`, `SHAPE`, `STYLE_CLS`, `TRANSFORM`, `WIDTH`, `HEIGHT`) VALUES ('P4', '', 'rect', 'box P4', 'translate(0,0)', '40', '40');


-- 공통코드테이블 하나로 관리



/*  ====================================================================  */

-- 공통코드
CREATE TABLE CMMN_CODE
(
	GRP_CODE		VARCHAR(20)	NULL, /* 그룹코드 */
	PARENT_CODE 	VARCHAR(20)		NOT NULL	, /* 부모코드(대분류코드) */	
	CODE			VARCHAR(20)	NOT NULL, /* 코드(소분류코드) */
	CODE_NM			VARCHAR(60)	NULL	, /* 코드명 */
	CODE_DC			VARCHAR(200)	NULL	, /* 코드설명 */
	USE_AT			CHAR(1)		NULL	, /* 사용여부 */
	SORT			INT(3)		NULL	,
	FRST_REGIST_DT	DATETIME	NULL	, /* 처음등록일시 */
	FRST_REGISTER 	VARCHAR(20)	NULL	, /* 처음등록자 */
	LAST_REGIST_DT	DATETIME	NULL	, /* 마지막등록일시 */
	LAST_REGISTER 	VARCHAR(20)	NULL	, /* 마지막등록자 */
	PRIMARY KEY (PARENT_CODE,CODE)
)
;

CREATE UNIQUE INDEX CMMN_CODE_PK ON CMMN_CODE
(
	PARENT_CODE,
	CODE
)
;

-- 'PRK_CELL_TYPE', 'P0', '기본', '기본영역(주차장)', 'Y', '0', NULL, NULL, NULL, NULL
-- 'PRK_CELL_TYPE', 'P1', '소유', '소유하고있는영역(주차장)', 'Y', '1', NULL, NULL, NULL, NULL
-- 'PRK_CELL_TYPE', 'P2', '미소유', '소유하지않은영역(주차장)', 'Y', '2', NULL, NULL, NULL, NULL
-- 'PRK_CELL_TYPE', 'P3', '타겟영역', '조회타겟영역(주차장)', 'Y', '3', NULL, NULL, NULL, NULL
-- 'PRK_CELL_TYPE', 'P4', '엘리베이터', '엘리베이터영역(주차장)', 'Y', '4', NULL, NULL, NULL, NULL
-- 'PRK_CELL_TYPE', 'P5', '기타', '기타영역(주차장)', 'Y', '5', NULL, NULL, NULL, NULL
-- 'ROOT', 'PRK_CELL_TYPE', '주차장 CELL 타입', '주차장 도면에서 CELL 타입을 구분한다.', 'Y', '0', NULL, NULL, NULL, NULL





-- 사용자정보테이블

CREATE TABLE USER_INFO
(
	USER_ID		VARCHAR(20) NOT NULL
	,PASSWD	    VARCHAR(100)
	,EMAIL	    VARCHAR(50)
	,USER_AUTH   VARCHAR(10)
	,USER_KIND   VARCHAR(15)
	,USER_NM	    VARCHAR(15)
	,PHONE	    VARCHAR(12)
	,PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX USER_INFO_PK ON USER_INFO
(
	USER_ID
);

-- 기본게시판
CREATE TABLE BOARD
( 
	B_NO VARCHAR(10) NOT NULL,
	B_TYPE CHAR(2) NOT NULL,
	TITLE VARCHAR(150) NOT NULL,
	CONTENT VARCHAR(2000) NULL,
	REG_DT CHAR(20) NOT NULL,
	REG_USER_ID VARCHAR(15) NOT NULL,
	PRIMARY KEY (B_NO)
);

CREATE UNIQUE INDEX BOARD_PK ON BOARD
(
	B_NO
);

-- 게시판 첨부파일
CREATE TABLE BOARD_ATTACH
( 
	B_NO VARCHAR(10) ,
	FILE_INNB VARCHAR(10) ,
	FILE_PATHE VARCHAR(200) ,
	FILE_NM VARCHAR(100) ,
	DELETE_YN CHAR(1) ,
	REG_DT CHAR(20) ,
	REG_USER_ID VARCHAR(20) ,
	PRIMARY KEY (B_NO,FILE_INNB)
);
CREATE UNIQUE INDEX BOARD_ATTACH_PK ON BOARD_ATTACH
(
	B_NO,FILE_INNB
);

-- 판매차량정보
CREATE TABLE SELL_CAR_INFO
( 
	SELL_CAR_INNB VARCHAR(10) NOT NULL,
	CAR_DIV VARCHAR(15) NOT NULL,
	BRAND INT(9) NOT NULL,
	SERIES INT(9) NOT NULL,
	MODEL INT(9) NULL,
	LEVEL INT(9) NULL,
	MISSION VARCHAR(15) NULL,
	FURE VARCHAR(15) NULL,
	COLOR VARCHAR(15) NULL,
	REGION VARCHAR(15) NULL,
	SPOT VARCHAR(15) NULL,
	COMPANY VARCHAR(15) NULL,
	CC INT(5) NULL,
	USED_YEAR VARCHAR(6) NULL,
	USED_DIS INT(7) NULL,
	CAR_NUM VARCHAR(10) NOT NULL,
	OWNER VARCHAR(15) NOT NULL,
	OWNER_PHONE VARCHAR(12) NOT NULL,
	SALE_YN VARCHAR(1) NULL,
	PRKPLCE_CODE VARCHAR(6) NULL,
	PRKPLCE_FLR_CODE VARCHAR(6) NULL,
	CELL_MAPNG_ID VARCHAR(50) NULL,
	HOLD_YN VARCHAR(1) NULL,
	PRIMARY KEY (SELL_CAR_INNB)

);
CREATE UNIQUE INDEX SELL_CAR_INFO_PK ON SELL_CAR_INFO
(
	SELL_CAR_INNB
);

-- 차량사진테이블
CREATE TABLE CAR_PIC
( 
	SELL_CAR_INNB VARCHAR(10) ,
	PIC_INNB VARCHAR(10) ,
	FILE_PATH VARCHAR(200) ,
	FILE_NM VARCHAR(100) ,
	DELETE_YN CHAR(1) ,
	REG_DT CHAR(20) ,
	REG_USER_ID VARCHAR(20) ,

	PRIMARY KEY (SELL_CAR_INNB,PIC_INNB )

);
CREATE UNIQUE INDEX CAR_PIC_PK ON CAR_PIC
(
	SELL_CAR_INNB,PIC_INNB
);


-- 차량 모델 정보 코드테이블
CREATE TABLE CAR_MODEL_INFO
(
	CAR_COMP	VARCHAR(20) NOT NULL
	,MODEL_CODE VARCHAR(20) NOT NULL
	,MODEL_NM	VARCHAR(50)	NOT NULL
	,CAR_KIND	VARCHAR(20)
	,CAR_OUTLINE VARCHAR(20)
	,CAR_FURE	VARCHAR(20)
	,CAR_MSN	VARCHAR(20)
	
	, PRIMARY KEY ( CAR_COMP , MODEL_CODE )
);
CREATE UNIQUE INDEX CAR_MODEL_INFO_PK ON CAR_MODEL_INFO
(
	CAR_COMP , MODEL_CODE
);

-- 차량 정보 코드테이블
CREATE TABLE CAR_INFO
( 
	INFO_CD INT(9) NOT NULL,
	INFO_CD_NM VARCHAR(50) NOT NULL,
	P_INFO_CD INT(9) NULL,
	GRP_DIV VARCHAR(15) NULL,
	SORT INT(9) NULL,


	PRIMARY KEY ( INFO_CD )

);
CREATE UNIQUE INDEX CAR_INFO_PK ON CAR_INFO
(
	INFO_CD
);


-- 메뉴 관리 코드테이블
CREATE TABLE MENU_INFO
( 
	MENU_ID CHAR(8) NOT NULL,
	MENU_DIV CHAR(2) ,
	MENU_NM VARCHAR(40) ,
	MENU_KIND_CD CHAR(2) ,
	MENU_PID CHAR(8) ,
	MENU_URL VARCHAR(100) ,
	MENU_IMG1 VARCHAR(100) ,
	MENU_IMG2 VARCHAR(100) ,
	MENU_ICON VARCHAR(20) ,
	SORT INT(3) ,
	USE_AUTH INT(4) ,
	USE_AT CHAR(1) ,
	REG_DT CHAR(20) ,
	REG_USER_ID VARCHAR(20) ,



	PRIMARY KEY ( MENU_ID )

);
CREATE UNIQUE INDEX MENU_INFO_PK ON MENU_INFO
(
	MENU_ID
);

INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `MENU_KIND_CD`, `MENU_URL`, `MENU_ICON`, `SORT`, `USE_AT`) VALUES ('M0000', 'HOME', '', '/index.do', 'home', '0', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `SORT`, `USE_AT`) VALUES ('M0001', '정보조회', '1', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `SORT`, `USE_AT`) VALUES ('M0002', '정보관리', '2', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `SORT`, `USE_AT`) VALUES ('M0003', '게시판', '3', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `SORT`, `USE_AT`) VALUES ('M0004', '운영관리', '4', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `MENU_PID`, `SORT`, `USE_AT`) VALUES ('M0005', '차량조회', 'M0001', '0', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `MENU_PID`, `SORT`, `USE_AT`) VALUES ('M0006', '주차조회', 'M0001', '1', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `MENU_PID`, `SORT`, `USE_AT`) VALUES ('M0007', '차량정보관리', 'M0002', '0', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `MENU_PID`, `SORT`, `USE_AT`) VALUES ('M0008', '주차정보관리', 'M0002', '1', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `MENU_PID`, `SORT`, `USE_AT`) VALUES ('M0009', '공지사항', 'M0003', '0', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `MENU_PID`, `SORT`, `USE_AT`) VALUES ('M0010', '문의사항', 'M0003', '1', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `MENU_PID`, `SORT`, `USE_AT`) VALUES ('M0011', '사용자관리', 'M0004', '0', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `MENU_PID`, `MENU_URL`, `SORT`, `USE_AT`) VALUES ('M0012', '메뉴관리', 'M0004', '/mgr/mgr0001/menuList.do', '1', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `MENU_PID`, `MENU_URL`, `SORT`, `USE_AT`) VALUES ('M0013', '코드관리', 'M0004', '', '2', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `MENU_PID`, `MENU_URL`, `MENU_ICON`, `SORT`, `USE_AT`) VALUES ('M0014', '공통코드관리', 'M0013', '/mgr/mgr0002/codeList.do', 'carat-r', '0', 'Y');
INSERT INTO `lfc`.`menu_info` (`MENU_ID`, `MENU_NM`, `MENU_PID`, `SORT`, `USE_AT`) VALUES ('M0015', '차량코드관리', 'M0013', '1', 'Y');

update menu_info set use_auth = 15;

